import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';
import 'package:rest_api/models/Autogenerated.dart';

class CardWidget extends StatefulWidget {
  final bool showTitle;
  final bool showDescription;
  final RelatedTopics? relatedTopics;

  const CardWidget(
      {super.key,
      this.showTitle = false,
      this.showDescription = false,
      this.relatedTopics});

  @override
  State<CardWidget> createState() => _CardWidgetState();
}

class _CardWidgetState extends State<CardWidget> {
  @override
  Widget build(BuildContext context) {
    var screenSize = MediaQuery.of(context).size;
    bool isTablet = screenSize.shortestSide >= 600;

    return Padding(
      padding: const EdgeInsets.all(10),
      child: Container(
        padding: EdgeInsets.all(10),
        width: double.infinity,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(16),
          border: Border.all(width: 1, color: Colors.black),
        ),
        child: Padding(
          padding: EdgeInsets.only(bottom: 20),
          child:
              Column(crossAxisAlignment: CrossAxisAlignment.center, children: [
            const SizedBox(
              height: 5,
            ),
            ClipRRect(
              borderRadius: BorderRadius.circular(100),
            ),
            const SizedBox(
              height: 20,
            ),
            const SizedBox(
              width: 10,
            ),
            widget.showTitle == true || isTablet
                ? Column(
                    children: [
                      const Text(
                        "Tilte",
                        style: TextStyle(
                            fontSize: 15, fontWeight: FontWeight.bold),
                      ),
                      Align(
                        alignment: Alignment.center,
                        child: HtmlWidget(
                          widget.relatedTopics?.result ?? "",
                        ),
                      )
                    ],
                  )
                : SizedBox(),
            const SizedBox(
              height: 10,
            ),
            const SizedBox(
              width: 10,
            ),
            widget.showDescription == true || isTablet
                ? Column(
                    children: [
                      const Text(
                        "Description",
                        style: TextStyle(
                            fontSize: 15, fontWeight: FontWeight.bold),
                      ),
                      const SizedBox(
                        height: 5,
                      ),
                      Padding(
                        padding: const EdgeInsets.only(left: 16, right: 16),
                        child: Text(
                          widget.relatedTopics?.text ?? "",
                          textAlign: TextAlign.center,
                        ),
                      )
                    ],
                  )
                : SizedBox()
          ]),
        ),
      ),
    );
  }
}
