import 'package:flutter/material.dart';
import 'package:rest_api/helpers.dart';
import 'package:rest_api/models/Autogenerated.dart';
import 'package:rest_api/widget/card.dart';
class Detail extends StatefulWidget {

  final RelatedTopics? userDetails;
  const Detail({super.key  , this.userDetails});

  @override
  State<Detail> createState() => _DetailState();
}

class _DetailState extends State<Detail> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar( 
       title: Padding(
         padding: const EdgeInsets.only(right: 30),
         child: Center(child: Text("Detail Page" , style: TextStyle(fontSize: 20 , fontWeight: FontWeight.bold),)),
       ),),
       body: Column(
         children: [
           SizedBox(
            height: 20,
           ),

           Container(
     
             child: CardWidget(
              relatedTopics: widget.userDetails,
               showDescription: true,
             ),
           ),
         ],
       ) );
  
  }
}